[TELEGRAM]
# Token bot Telegram cua ban
BotToken=8868470986:AAEOtgjpH56MoOhpywSfbAceKLCIKdFNgj0

# Chat ID cua ban (de nhan thong bao)
ChatID=1184601478

[ANYDESK]
# Mat khau AnyDesk ban muon dat (Phai co chu hoa, chu thuong, so, ky tu dac biet)
Password=Cds@1124
